// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testing.Data;

#nullable disable

namespace Testing.Migrations
{
    [DbContext(typeof(CalculatorDBContext))]
    [Migration("20250715064333_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Testing.CalculatorEntitiy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Operand1")
                        .HasColumnType("int");

                    b.Property<int>("Operand2")
                        .HasColumnType("int");

                    b.Property<int>("result")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CalculatorEntitiys");
                });
#pragma warning restore 612, 618
        }
    }
}
